version: "3"

services:
  backend:
    build: ./
    command: npm start
    working_dir: /var/www/renter-backend
    ports:
      - "5000:5000"
    volumes:
      - ./:/var/www/renter-backend
  redis-server:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  mongo-server:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
