services:
  node:
    # image: "node"
    build: ./
    command: npm start
    working_dir: /var/www/renter-backend
    ports:
      - "5000:5000"
  redis-server:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  mongo-server:
    image: mongo
    restart: always
    ports:
      - "27017:27017"